name: Ejecutar API de Clima

on:
  schedule:
    - cron: '1 15 * * *'  # Se ejecuta todos los días a las 15:01 UTC
  workflow_dispatch:  # Permite ejecución manual

env:
  API_KEY: ${{ secrets.API_KEY }}
  SF_USER: ${{ secrets.SF_USER }}
  SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_DATABASE: ${{ secrets.SF_DATABASE }}
  SF_SCHEMA_CT: ${{ secrets.SF_SCHEMA_CT }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

jobs:
  ejecutar_api:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Pipenv y dependencias
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev  # Instala dependencias del Pipfile

      - name: Verificar instalación de Uvicorn
        run: |
          pipenv run uvicorn --version

      - name: Iniciar API de FastAPI en segundo plano
        run: |
          pipenv run uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Esperar unos segundos para que la API arranque

      - name: Mostrar logs de la API (opcional)
        run: |
          cat nohup.out || true  # Muestra los logs de la API si existen
